name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build .NET App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: script
      run: ls -lah
    
    
#   package:
#     name: Package App
#     runs-on: ubuntu-latest
#     steps:
#     - name: Publish
#       run: dotnet publish -c Release -o website
#     - name: Upload a Build Artifact
#       uses: actions/upload-artifact@v3.1.0
#       with:
#         name: WebApp
#         path: website/**
#         if-no-files-found: warn

  # deploy:
  #   name: Deploying .NET App
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Azure WebApp
  #     uses: Azure/webapps-deploy@v2
  #     with:
  #       app-name: MyWebApp
    
